apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-server.fullname" . }}-secret
  labels:
    {{- include "mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  openai_api_key: {{ .Values.secrets.openai_api_key | b64enc }}
  snowflake_password: {{ .Values.secrets.snowflake_password | b64enc }}
  datahub_token: {{ .Values.secrets.datahub_token | b64enc }}
