repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: '^uv\.lock$'
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.11
        types: [python]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.1
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, postgres]
      - id: sqlfluff-fix
        args: [--dialect, postgres]
        stages: [manual]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  # Rule of Three duplicate code checker
  - repo: local
    hooks:
      - id: rule-of-three-check
        name: Rule of Three Duplicate Code Check
        entry: ./tools/check_duplicates.sh
        args: ['--max-impact', '5.0', '--fail-on-duplication']
        language: system
        pass_filenames: false
        stages: [pre-push]  # Only run on pre-push to avoid slowing down commits
        exclude: ^(tests/|docs/)
