global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@example.com'
  slack_api_url: '${SLACK_API_URL}'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
    - match:
        severity: warning
      receiver: 'slack-warning'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'

  - name: 'slack-critical'
    slack_configs:
      - api_url: '${SLACK_API_URL}'
        channel: '#alerts-critical'
        title: 'CRITICAL: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        username: 'Data Stack Alerts'
        icon_emoji: ':rotating_light:'
        color: 'danger'
        fields:
          - title: 'Component'
            value: '{{ .CommonLabels.component }}'
            short: true
          - title: 'Instance'
            value: '{{ .CommonLabels.instance }}'
            short: true

  - name: 'slack-warning'
    slack_configs:
      - api_url: '${SLACK_API_URL}'
        channel: '#alerts-warning'
        title: 'WARNING: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        username: 'Data Stack Alerts'
        icon_emoji: ':warning:'
        color: 'warning'
        fields:
          - title: 'Component'
            value: '{{ .CommonLabels.component }}'
            short: true
          - title: 'Instance'
            value: '{{ .CommonLabels.instance }}'
            short: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
