name: 'freelancer_analytics'
version: '1.0.0'
config-version: 2

# Require dbt 1.10.0 or higher
require-dbt-version: ">=1.10.0"

# This setting configures which "profile" dbt uses for this project.
profile: 'freelancer_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  freelancer_analytics:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
    incremental:
      +materialized: incremental

# Configuring seeds
seeds:
  freelancer_analytics:
    +quote_columns: false

# Configuring snapshots
snapshots:
  freelancer_analytics:
    +target_schema: snapshots

vars:
  # dbt_expectations configurations
  dbt_expectations_warn_if_not_tested: false

  # Environment-specific vars
  start_date: '2023-01-01'
  end_date: '2024-12-31'

# Hooks for DataHub integration
on-run-end:
  - "{{ register_with_datahub() }}"

# Post-hooks for dbt_artifacts (disabled for DuckDB compatibility)
# on-run-start:
#   - "{{ dbt_artifacts.upload_results() }}"
#
# on-run-end:
#   - "{{ dbt_artifacts.upload_results() }}"
