#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE metabase;
    CREATE DATABASE airflow;
    CREATE DATABASE meltano;
    GRANT ALL PRIVILEGES ON DATABASE metabase TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE airflow TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE meltano TO $POSTGRES_USER;
EOSQL
